# -*- coding: utf-8 -*-
"""Trader Behavior Analysis Using Market Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DHOpVJZM29C8lIg3SUcfHM709UuIdnk
"""

import os
import pandas as pd
import requests

dataset = "dataset"
os.makedirs(dataset , exist_ok=True)
def dataset_HD():
    print("Downloading HIstorical Data...")
    file_id = "1IAfLZwu6rJzyWKgBToqwSmmVYU6VbjVs"
    url = f"https://drive.google.com/uc?export=download&id={file_id}"
    path = os.path.join(dataset, "Historical_Data.csv")
    r = requests.get(url)
    with open(path, "wb") as f:
        f.write(r.content)

    print("Download Completed")

dataset_HD()

trader = pd.read_csv("dataset/Historical_Data.csv")

trader.head()

trader.info()

trader["Timestamp IST"] = pd.to_datetime(trader["Timestamp IST"], dayfirst=True)
trader["date"] = trader["Timestamp IST"].dt.date
trader["time"] = trader["Timestamp IST"].dt.time

trader.info()

!pip install gdown

import gdown
import os

dataset = "dataset"
os.makedirs(dataset, exist_ok=True)

url = "https://drive.google.com/uc?id=1PgQC0tO8XN-wqkNyghWc_-mnrYv_nhSf"

output = "dataset/Fear_Greed_Index.csv"

gdown.download(url, output, quiet=False)

sentiment = pd.read_csv("dataset/Fear_Greed_Index.csv")

sentiment.head()

sentiment.info()

sentiment["date"] = pd.to_datetime(sentiment["date"])
sentiment["date"] = sentiment["date"].dt.date

data = pd.merge(trader , sentiment, on="date" , how="left")
data.head()

data["classification"].value_counts()

data.isnull().sum()

data["profit"] = data["Closed PnL"] > 0

data["trade_value"] = data["Execution Price"] * data["Size Tokens"]

data["hour"] = data["Timestamp IST"].dt.hour

data.groupby("classification")["Closed PnL"].mean()

data.groupby("classification")["profit"].mean()

data.columns.tolist()

data.groupby("classification")["Size USD"].mean()

data.groupby("Side")["Closed PnL"].mean()

data["hour"].value_counts().sort_index()

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="hour", data=data)

plt.title("Trading Activity by Hour")

plt.show()

sns.boxplot(x="classification", y="Closed PnL", data=data)

plt.title("Profit Distribution by Market Sentiment")

plt.xticks(rotation=45)

plt.show()

sns.boxplot(x="classification", y="Size USD", data=data)

plt.title("Trade Size Distribution by Market Sentiment")

plt.xticks(rotation=45)

plt.show()

data.isnull().sum()

data = data.dropna(subset=["classification"])

data['value'].fillna(data['value'].mean(), inplace=True)

data['Timestamp'].fillna(data['Timestamp'].mode()[0], inplace=True)

order = ["Extreme Fear","Fear","Neutral","Greed","Extreme Greed"]

sns.boxplot(x="classification", y="Closed PnL", data=data, order=order)

numeric = data[["Closed PnL","Size USD","trade_value","profit"]]

sns.heatmap(numeric.corr(), annot=True)

plt.title("Correlation Between Trading Metrics")

plt.show()

features = [
    "Size USD",
    "Execution Price",
    "trade_value",
    "hour",
    "value"
]

X = data[features]
y = data["profit"]

y.value_counts()

from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, predictions)

print("Model Accuracy:", accuracy*100)

print(classification_report(y_test, predictions))

import pandas as pd
import matplotlib.pyplot as plt

importance = pd.Series(
    model.feature_importances_,
    index=features
)

importance.sort_values().plot(kind="barh")

plt.title("Feature Importance for Profit Prediction")

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test, predictions)

sns.heatmap(cm, annot=True, fmt="d")

plt.title("Confusion Matrix")

plt.show()

"""**Key Insights**

Insight 1

Traders achieve the highest win rate during Extreme Greed sentiment, indicating strong bullish momentum improves trading outcomes.

Insight 2

Extreme Fear sentiment results in lower profitability due to panic-driven trading behavior.

Insight 3

Trade sizes tend to increase during Greed markets, suggesting higher risk appetite among traders.

Insight 4

Trading activity peaks during specific hours, likely corresponding to periods of high market liquidity.

A Random Forest classifier was trained to predict trade profitability.
The model learns relationships between trade size, execution price,
market sentiment value, and trading time.

Feature importance analysis shows which factors influence profitable trades.
"""